# Generated by Django 3.0 on 2020-01-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='comment',
            name='nickname',
            field=models.CharField(default='', max_length=30),
        ),
    ]
