# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-21 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('intro', models.TextField()),
                ('context', models.TextField()),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('atype', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleType'),
        ),
    ]
