# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('context', models.TextField()),
                ('article_type', models.CharField(max_length=30)),
            ],
        ),
    ]
