# Generated by Django 3.0 on 2020-01-05 16:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='n_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='n_visits',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ArticleStatsRecord',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ip', models.GenericIPAddressField()),
                ('ua', models.CharField(max_length=300)),
                ('record_type', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='article.Article')),
            ],
        ),
    ]
