# Generated by Django 3.0 on 2020-01-01 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20200101_1035'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='readeritem',
            name='item_reader_ip_a6abed_idx',
        ),
        migrations.RenameField(
            model_name='readeritem',
            old_name='item_uuid',
            new_name='item',
        ),
        migrations.AddIndex(
            model_name='readeritem',
            index=models.Index(fields=['ip'], name='item_reader_ip_255e3f_idx'),
        ),
    ]
